[package]
name = "cubic-render"
version.workspace = true
edition.workspace = true

[features]
default = ["wgpu"]
web = ["dep:wasm-bindgen", "dep:js-sys", "dep:web-sys"]
wgpu = ["dep:winit", "dep:wgpu", "dep:pollster", "dep:log", "dep:bytemuck"]

[dependencies]
bytemuck = { version = "1", optional = true }
cubic-core = { path = "../cubic-core" }
log = { version = "0.4", optional = true }
pollster = { version = "1.0", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
js-sys = { version = "0.3", optional = true }
web-sys = { version = "0.3", optional = true, features = [
    "CanvasRenderingContext2d",
] }
wgpu = { version = "30", optional = true }
winit = { version = "0.30", optional = true }

[dev-dependencies]
env_logger = "0.11"

[[example]]
name = "basic"
required-features = ["wgpu"]

[[example]]
name = "draw2d"
required-features = ["wgpu"]

[[example]]
name = "bench"
required-features = ["wgpu"]

[lints]
workspace = true