[package]
name = "cubic-render"
version.workspace = true
edition.workspace = true

[features]
web = ["dep:wasm-bindgen", "dep:js-sys", "dep:web-sys"]

[dependencies]
cubic-core = { path = "../cubic-core" }
wasm-bindgen = { version = "0.2", optional = true }
js-sys = { version = "0.3", optional = true }
web-sys = { version = "0.3", optional = true, features = [
    "CanvasRenderingContext2d",
] }

[lints]
workspace = true